name: 🔍 Preview Deployment

on:
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages-preview-${{ github.event.pull_request.number }}"
  cancel-in-progress: false

jobs:
  build-and-preview:
    runs-on: ubuntu-latest
    
    steps:
    - name: 📦 Checkout repository
      uses: actions/checkout@v4
      
    - name: 🔧 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: 📥 Install dependencies
      run: npm ci
      
    - name: 🎨 Generate favicons
      run: npm run prebuild
      
    - name: 🏗️ Build Next.js application
      run: npm run build
      env:
        NODE_ENV: production
        BASE_PATH: "/portfolio"
        
    - name: 📤 Export static site
      run: npm run export
      
    - name: 📝 Add .nojekyll file
      run: touch ./out/.nojekyll
      
    - name: ⚙️ Setup Pages
      uses: actions/configure-pages@v4
      
    - name: 📦 Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './out'
        
    - name: 🚀 Deploy to GitHub Pages Preview
      id: deployment
      uses: actions/deploy-pages@v4
      
    - name: 💬 Comment PR with preview link
      uses: actions/github-script@v7
      if: github.event_name == 'pull_request'
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `🚀 **Preview deployed successfully!**\n\n🔗 **Preview URL:** ${{ steps.deployment.outputs.page_url }}\n\nThis preview will be automatically updated when you push new commits to this PR.`
          })
